from data import descriptive

desc = descriptive.DBDescriptor()

tw = desc.tweets()
ori = desc.originals()
male_ori = desc.male_originals()
fem_ori = desc.female_originals()
men = desc.mentions()
rep = desc.replies()
print('Tweets (total):', tw)
print('\tOriginal tweets:', ori)
print('\t\tBy males:', male_ori)
print('\t\tBy females:', fem_ori)
print('\tMention tweets:', men)
print('\tReply tweets:', rep)
print()

us = desc.users()
pol = desc.politicians()
pol_m, pol_f = desc.politicians_per_gender()
ind = desc.individuals()
ind_m, ind_f = desc.individuals_per_gender()
print('Users (total):', us)
print('\tPolitician users:', pol)
print('\t\tMale politicians:', pol_m)
print('\t\tFemale politicians:', pol_f)
print('\tIndividual users:', ind)
print('\t\tMale individuals:', ind_m)
print('\t\tFemale individuals:', ind_f)
print()

pol_aut = desc.politicians_per_aut()
print('Autonomy : Politicians')
for a,c in pol_aut.items():
    print(a, ':', c)
print()

results = desc.replies_per_genders()
print('Replies per gender:')
print('                       Respondent')
print('                 Male --- Female --- Unknown')
print('         Male |', str(results[0,0]),' | ', str(results[0,1]), ' | ', str(results[0,2]))
print('Author:  Female |', str(results[1,0]),' | ', str(results[1,1]), ' | ',str(results[1,2]))
print('         Unknown |', str(results[2,0]),' | ', str(results[2,1]), ' | ', str(results[2,2]))
print()

m, f = desc.followers_per_gender()
print('Followers per gender:')
print('\tMale politicians:', m)
print('\tFemale politicians:', f)
print()

m, f = desc.favorites_received_per_gender()
print('Favorites per gender:')
print('\tMale politicians:', m)
print('\tFemale politicians:', f)
print()

m, f = desc.retweets_received_per_gender()
print('Retweets per gender:')
print('\tMale politicians:', m)
print('\tFemale politicians:', f)
print()
